title: Pcrab 的日常
# 最后不要加上斜杠 /
site: https://pcrab.ml
# favicon.ico 和 icon.png 都存放在 source 文件夹中
favicon: /favicon.ico
icon: /images/icon.png

language:
  - en
  - zh_cn

author:
  name: Pcrab
  self_intro: 一个普通的大学生，爱好计算机，懒
  github: Pcrab
  email: pxw0717@gmail.com
  telegram: Pcrab


#仅提供cc协议
copyright:
  #显示版权信息，0为关闭，1为对所有post生效，2为对文章中有"copyright: true"的文章才生效
  open: 1
  #是否可被商用，0为不可，1为可
  commercial: 0
  #是否可被演绎，0为不可，1为在相同方式下可，2为可
  derivative: 1

# There are two comment framework to be choosen, Valine and Disqus.
comment:
  # Please select Disqus or Valine.
  Select: Disqus
  # Please visit https://valine.js.org/ to lean how to get appid and appkey.
  Valine:
    appid: JYGJAIgDkSKSDgp5pUPfyxoO-MdYXbMMI
    appkey: T36nhlVVvMa1c33Tee3F13JM
    verify: true
  # Recommended
  Disqus:
    short-name: pcrab-blog
    # If you need proxy, please visit https://github.com/fooleap/disqus-php-api to learn how to do so.
    # Important: you need a VPS which can connect to Disqus.
    needProxy: true


#网站成立时间，若大于等于当前年份则不会显示
startYear: 2019

#显示页脚主题信息
showTheme: true
